ledger/urls.py
from django.contrib import admin
from django.urls import path, include

from ledger_ui.views import index

urlpatterns = [
    path('', index),
    path('admin/', admin.site.urls),
    path('ledger/ui/', include('ledger_ui.urls')),
    path('ledger/submit/', include('ledger_submit.urls')),
    path('ledger/query/', include('ledger_query.urls')),
    path('accounts/', include('accounts.urls')),
]

ledger_query/urls.py
from django.urls import path

from . import views

app_name = 'ledger_query'
urlpatterns = [
    path('transactions/', views.transactions, name='transactions'),
]

ledger_ui/urls.py
from django.urls import path

from . import views

app_name = 'ledger_ui'
urlpatterns = [
    path('', views.index, name='index'),
    path('journal/', views.journal, name='journal'),
    path('submit/', views.submit, name='submit'),
    path('balance/', views.balance, name='balance'),
    path('charts/', views.charts, name='charts'),
    path('register/', views.register, name='register'),
    path('rules/', views.RuleIndexView.as_view(), name='rules'),
    path('rule/', views.RuleCreateView.as_view(), name='rule'),
    path('rule/<int:pk>/', views.RuleEditView.as_view(), name='rule'),
    path('rule/<int:pk>/delete/', views.RuleDeleteView.as_view(), name='rule_delete'),
]

ledger_ui/models.py
from django.contrib.auth.models import User
from django.db import models

import pickle


class LedgerPath(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        primary_key=True,
        related_name="ledger_path",
    )
    path = models.CharField(max_length=1024)

    def __str__(self):
        return "{}: {}".format(self.user, self.path)


class Undo(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        primary_key=True,
    )

    last_entry_pickle = models.BinaryField()
    old_position = models.PositiveIntegerField()
    new_position = models.PositiveIntegerField()

    @property
    def last_entry(self):
        return pickle.loads(self.last_entry_pickle)

    @last_entry.setter
    def last_entry(self, entry):
        self.last_entry_pickle = pickle.dumps(entry)

ledger_ui/forms.py
from django import forms
from django.conf import settings
from django.forms import formset_factory, BaseFormSet
from django.utils.translation import gettext as _

import datetime
import re

from . import fields
from ledger_submit.models import Rule


class AccountForm(forms.Form):

    name = forms.CharField(widget=fields.ListTextWidget(
        name='accounts',
        data_list=None,
        attrs={'class': 'name-input'},
    ))
    amount = forms.DecimalField(
        decimal_places=2,
        required=False,
        widget=forms.NumberInput(attrs={'class': 'amount-input'}),
    )
    currency = forms.CharField(
        required=False,
        widget=fields.ListTextWidget(
            name='currencies',
            data_list=None,
            attrs={
                'tabindex': -1,
                'size': 5,
                'class': 'currency-input',
            },
        ),
    )

    field_order = ['name', 'amount', 'currency']

    def __init__(self, *args, default_currency=None, **kwargs):
        if default_currency is None:
            default_currency = settings.LEDGER_DEFAULT_CURRENCY
        initial = kwargs.pop('initial', {})
        if initial.get('amount') is None:
            initial['currency'] = default_currency
        super().__init__(*args, initial=initial, **kwargs)


class BaseAccountFormSet(BaseFormSet):

    def clean(self):
        if any(self.errors):
            return

        missing_amount_count = [
            form.cleaned_data.get('amount')
            for form in self.forms
        ].count(None)
        if missing_amount_count > 1:
            raise forms.ValidationError(
                _("Only one account can have the amount omitted.")
            )


AccountFormSet = formset_factory(
    AccountForm,
    formset=BaseAccountFormSet,
    min_num=2,
    extra=0,
    validate_min=True,
)


class SubmitForm(forms.Form):

    date = forms.DateField(initial=datetime.date.today)
    payee = forms.CharField(max_length=512)
    note = forms.CharField(
        required=False,
        widget=forms.Textarea(
            attrs={
                'tabindex': -1,
                'rows': 1,
                'cols': 20,
            },
        ),
    )

    amend = forms.BooleanField(
        # Even though it's a BooleanField, the HiddenInput widget is
        # textual. False would be cast to "False" which is true, so
        # let's use a false string instead.
        initial='',
        required=False,
        widget=forms.HiddenInput(),
    )
    save_rule = forms.BooleanField(
        label="Save as a new rule",
        initial=False,
        required=False,
    )

    def top_fields(self):
        return (
            self[field]
            for field in ['date', 'payee', 'note']
        )

    def __init__(self, *args, payees, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['payee'].widget = fields.ListTextWidget(
            name='payees',
            data_list=payees,
            attrs={'autofocus': ''},
        )


class RuleModelForm(forms.ModelForm):

    class Meta:
        model = Rule
        exclude = ['user']

    def conditions(self):
        return (
            self[field]
            for field in ['payee', 'note']
        )

    def actions(self):
        return (
            self[field]
            for field in ['new_payee', 'new_note', 'account']
        )

    def __init__(self, *args, accounts, payees, user, **kwargs):
        super().__init__(*args, **kwargs)

        self.user = user

        self.fields['payee'].widget = fields.ListTextWidget(
            name='payee',
            data_list=map(re.escape, payees),
        )
        self.fields['note'].widget = forms.Textarea(
            attrs={
                'rows': 1,
                'cols': 20,
            },
        )
        self.fields['new_payee'].widget = fields.ListTextWidget(
            name='new_payee',
            data_list=payees,
        )
        self.fields['new_note'].widget = forms.Textarea(
            attrs={
                'rows': 1,
                'cols': 20,
            },
        )
        self.fields['account'].widget = fields.ListTextWidget(
            name='account',
            data_list=accounts,
        )

    def clean(self):
        errors = []
        cleaned_data = super().clean()

        payee = cleaned_data['payee']
        user = self.user
        try:
            Rule.objects.exclude(
                pk=self.instance.pk,
            ).get(
                payee=payee,
                user=user,
            )
        except Rule.DoesNotExist:
            pass
        else:
            errors.append(
                forms.ValidationError(
                    _("Non-unique data: payee=%(payee)s, user=%(user)s."),
                    params={'payee': payee, 'user': user},
                    code='invalid',
                )
            )

        if errors:
            raise forms.ValidationError(errors)

ledger_ui/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.db.models.functions import Lower
from django.http import Http404, HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView

import pandas as pd
import re

from .forms import SubmitForm, RuleModelForm, AccountFormSet
from .models import Undo
from ledger_submit.models import Rule
from utils import ledger_api


def index(request):
    return render(
        request,
        'ledger_ui/index.html',
    )


@login_required
def journal(request):
    if request.method == 'POST':
        if request.POST.get('revert'):
            undo = get_object_or_404(Undo, pk=request.user)

            ledger_path = request.user.ledger_path.path
            journal = ledger_api.Journal(ledger_path, undo)

            try:
                journal.revert()
            except journal.CannotRevert:
                return render(
                    request,
                    'ledger_ui/error/cannot_revert.html',
                    status=409,
                )

    entries = list(ledger_api.Journal(request.user.ledger_path.path))


    entry_filter = request.GET.get('filter', '')
    if entry_filter:
        entries = [
            entry
            for entry in entries
            if entry_filter.lower() in entry['body'].lower()
        ]

    count = request.GET.get('count', settings.LEDGER_ENTRY_COUNT)
    try:
        count = int(count)
    except ValueError:
        if count is not None and count != 'all':
            return HttpResponse(
                '<h1>Unprocessable Entity</h1> Bad count.',
                status=422,
            )
    if count != 'all' and len(entries) <= count:
        count = 'all'
    if count != 'all':
        entries = entries[-count:]

    reversed_sort = request.GET.get('reverse', 'true').lower() not in ['false', '0']
    if reversed_sort:
        entries = reversed(entries)

    ledger_path = request.user.ledger_path.path
    journal = ledger_api.Journal(ledger_path)
    try:
        undo = Undo.objects.get(pk=request.user)
    except Undo.DoesNotExist:
        pass
    else:
        journal.last_data = undo

    return render(
        request,
        'ledger_ui/journal.html',
        {
            'entries': entries,
            'reverse': reversed_sort,
            'count': count,
            'filter': entry_filter,
            'count_step': settings.LEDGER_ENTRY_COUNT,
            'can_revert': not entry_filter and journal.can_revert(),
        },
    )


@login_required
def charts(request):
    ledger_path = request.user.ledger_path.path

    csv = ledger_api.Journal(ledger_path).csv(
        '--real',
        '--monthly',
        '-X', settings.LEDGER_DEFAULT_CURRENCY,
    )
    df = pd.read_csv(
        csv,
        header=None,
        names=[
            'date', 'code', 'payee', 'account', 'currency', 'amount',
            'reconciled', 'note',
        ],
        usecols=['date', 'payee', 'account', 'amount'],
        parse_dates=['date'],
    )
    if len(df) == 0:
        return render(
            request,
            'ledger_ui/charts.html',
        )

    assets = df[df['account'].str.contains("^Assets:|^Liabilities:")]
    income = df[df['account'].str.contains("^Income:")]

    account_filter = request.GET.get('account_filter', '')
    if account_filter:
        expenses = df[df['account'].str.contains(
            account_filter,
            case=False,
        )].copy()
    else:
        expenses = df[df['account'].str.contains("^Expenses:")].copy()

    date_grouped_assets = assets[['date', 'amount']].groupby('date').sum()
    date_grouped_expenses = expenses[['date', 'amount']].groupby('date').sum()
    date_grouped_income = income[['date', 'amount']].groupby('date').sum()

    date_range = pd.date_range(df['date'].min(), df['date'].max(), freq='MS')
    date_grouped_assets = date_grouped_assets.reindex(date_range, fill_value=0)
    date_grouped_expenses = date_grouped_expenses.reindex(date_range, fill_value=0)
    date_grouped_income = date_grouped_income.reindex(date_range, fill_value=0)

    date_grouped_assets['amount'] = date_grouped_assets['amount'].cumsum()
    expenses['date'] = expenses['date'].dt.strftime("%Y-%m")

    return render(
        request,
        'ledger_ui/charts.html',
        {
            'dates': {'data': date_range.strftime('%Y-%m').to_series().to_list()},
            'expenses_totals': date_grouped_expenses['amount'].round(2).to_json(),
            'income_totals': (-date_grouped_income['amount']).round(2).to_json(),
            'expenses': (
                expenses[['date', 'account', 'amount']].to_json(
                    orient='table', index=False)),
            'assets': date_grouped_assets['amount'].round(2).to_json(),
            'account_filter': account_filter,
        },
    )


@login_required
def submit(request):
    ledger_path = request.user.ledger_path.path
    journal = ledger_api.Journal(ledger_path)
    ledger_errors = False

    try:
        accounts = journal.accounts()
        currencies = journal.currencies()
        payees = journal.payees()
    except journal.LedgerCliError as e:
        accounts = currencies = payees = []
        ledger_errors = e.__cause__

    if request.method == 'POST':
        form = SubmitForm(
            request.POST,
            payees=payees,
        )
        formset = AccountFormSet(
            request.POST,
        )
        if form.is_valid() and formset.is_valid():
            validated = form.cleaned_data
            entry = ledger_api.Entry(
                date=validated['date'],
                payee=validated['payee'],
                note=validated['note'],
                accounts=[
                    (account['name'], account['amount'], account['currency'])
                    for account in formset.cleaned_data
                    if account.get('name')
                ],
            )

            if validated['amend']:
                undo = get_object_or_404(Undo, pk=request.user)
                journal.last_data = undo

                if validated['save_rule']:
                    Rule.objects.create(
                        user=request.user,
                        payee=re.escape(undo.last_entry.payee),
                        note=(
                            undo.last_entry.note
                            if undo.last_entry.note != entry.note
                            else ''
                        ),
                        new_payee=entry.payee,
                        new_note=(
                            entry.note
                            if undo.last_entry.note != entry.note
                            else ''
                        ),
                        account=entry.accounts[0][0],
                    )

                try:
                    journal.revert()
                except journal.CannotRevert:
                    return render(
                        request,
                        'ledger_ui/error/cannot_revert.html',
                        status=409,
                    )

            old, new = journal.append(entry)
            Undo.objects.update_or_create(
                pk=request.user.id,
                defaults={
                    'last_entry': entry,
                    'old_position': old,
                    'new_position': new,
                },
            )
            return redirect('ledger_ui:journal')

    else:
        amend = request.GET.get('amend', 'false').lower() not in ['false', '0']
        if amend:
            last_entry = get_object_or_404(Undo, pk=request.user).last_entry
            form = SubmitForm(
                {
                    'date': last_entry.date,
                    'payee': last_entry.payee,
                    'note': last_entry.note,
                    'amend': True,
                },
                payees=payees,
            )
            default_currency = settings.LEDGER_DEFAULT_CURRENCY
            for account in last_entry.accounts:
                if account.amount is not None:
                    default_currency = account.currency
                    break
            formset = AccountFormSet(
                form_kwargs={
                    'default_currency': default_currency,
                },
                initial=[
                    account._asdict()
                    for account in last_entry.accounts
                ],
            )
        else:
            form = SubmitForm(payees=payees)
            formset = AccountFormSet(
                initial=[
                    {'name': settings.LEDGER_DEFAULT_TO},
                    {'name': settings.LEDGER_DEFAULT_FROM},
                ]
            )

    return render(
        request,
        'ledger_ui/submit.html',
        {
            'form': form,
            'formset': formset,
            'accounts': accounts,
            'currencies': currencies,
            'ledger_errors': ledger_errors,
        },
    )


@login_required
def balance(request):
    ledger_path = request.user.ledger_path.path

    csv = ledger_api.Journal(ledger_path).csv()
    df = pd.read_csv(
        csv,
        header=None,
        names=[
            'date', 'code', 'payee', 'account', 'currency', 'amount',
            'reconciled', 'note',
        ],
        usecols=['account', 'currency', 'amount'],
    )

    search = request.GET.get('filter', '')
    if search:
        df = df[df['account'].str.contains(search, case=False)]

    if len(df) == 0:
        return render(
            request,
            'ledger_ui/balance.html',
            {
                'accounts': [],
                'filter': search,
            },
        )

    balance = df.groupby(['account', 'currency']).sum()

ledger_ui/templates/ledger_ui/balance.html
{% extends "./base.html" %}

{% block title %}
  {{ block.super }} - Balance
{% endblock %}

{% block content %}
  <h2>Balance</h2>
  <form action="{{ request.path }}" method="GET">
    <input name="filter" type="text" value="{{ filter }}" />
    <input type="submit" value="Search" />
  </form>
  <table class="ledger-table">
    <tr>
      <th>Account</th>
      <th>Balance</th>
      <th>Currency</th>
    </tr>
    {% for key, amount in accounts.items %}
      <tr class="{% if amount == 0 %}null-balance{% endif %}
                 {% if amount < 0 %}negative-balance{% endif %}
                 ">
        <td>
          {% ifchanged %}
            <a href="{% url 'ledger_ui:register' %}?filter={{ key.0 }}"
               class="plain-link"
            >
              {{ key.0 }}
            </a>
          {% endifchanged %}
        </td>
        <td class="color-amount balance">
          {{ amount|floatformat:2 }}
        </td>
        <td class="color-amount">{{ key.1 }}</td>
      </tr>
    {% endfor %}
  </table>
{% endblock %}

ledger_ui/templates/ledger_ui/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <style>
     body { display: none; }
    </style>
    <link rel="stylesheet" type="text/css" href="{% static "style.css" %}">
    <link href="{% static "hamburgers.css" %}" rel="stylesheet">

    <meta property="og:title" content="Ledger Web">
    <meta property="og:image" content="{% static "icons/android-chrome-192x192.png" %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static "icons/apple-touch-icon.png" %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static "icons/favicon-32x32.png" %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static "icons/favicon-16x16.png" %}">
    <link rel="manifest" href="{% static "icons/site.webmanifest" %}">
    <link rel="mask-icon" href="{% static "icons/safari-pinned-tab.svg" %}" color="#5bbad5">
    <link rel="shortcut icon" href="{% static "icons/favicon.ico" %}">
    <meta name="apple-mobile-web-app-title" content="Ledger Web">
    <meta name="application-name" content="Ledger Web">
    <meta name="msapplication-TileColor" content="#0e5800">
    <meta name="msapplication-config" content="{% static "icons/browserconfig.xml" %}">
    <meta name="theme-color" content="#0e5800">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
      {% block title %}Ledger{% endblock %}
    </title>
    {% block head %}{% endblock %}
  </head>
  <body>
    {% include './components/menu.html' %}
    <main>
      {% block content %}{% endblock %}
    </main>
    <hr class="footer" />
    <footer class="footer">
      <a href="https://vifon.github.io/ledger-web/">Ledger Web</a>
      <span title="GNU GPLv3">© 2019–2022</span>
      <a href="https://github.com/vifon">Wojciech Siewierski</a>
    </footer>
  </body>
</html>

ledger_ui/templates/ledger_ui/charts.html
{% extends "./base.html" %}

{% load static %}

{% block title %}
  {{ block.super }} - Charts
{% endblock %}

{% block head %}
  <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script src="{% static "jquery.ui.touch-punch.min.js" %}"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.11/lodash.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
  <script src="{% static "Chart.min.js" %}"></script>
{% endblock %}

{% block content %}
  <h2>Charts</h2>

  <form action="{{ request.path }}" method="GET">
    <input name="account_filter" type="text" value="{{ account_filter }}" />
    <input type="submit" value="Filter Expenses" />
  </form>

  <div class="chart-container">
    <canvas id="timechart"></canvas>
  </div>

  <div class="time-controls">
    <div id="slider-range"></div>
    <div>
      <div style="float: left">
        <select id="range-select1">
          {% for date in dates.data %}
            <option
              {% if forloop.first %} selected="selected" {% endif %}
              value="{{ forloop.counter0 }}"
            >
              {{ date }}
            </option>
          {% endfor %}
        </select>
      </div>
      <div style="float: right">
        <select id="range-select2">
          {% for date in dates.data %}
            <option
              {% if forloop.last %} selected="selected" {% endif %}
              value="{{ forloop.counter0 }}"
            >
              {{ date }}
            </option>
          {% endfor %}
        </select>
      </div>
    </div>
    <div style="clear:both"></div>
  </div>

  <hr />
  <div>
    Sort by:
    <label>
      <input id="sort-by-labels" type="radio"
             name="chart-sort" value="label"
             checked
      >
      label
    </label>
    <label>
      <input id="sort-by-value" type="radio"
             name="chart-sort" value="value"
      >
      value
    </label>
  </div>
  <div class="chart-container">
    <canvas id="piechart"></canvas>
  </div>

  {{ dates|json_script:"dates-data" }}
  <script>
   const djangoExtract = function (name) {
     return JSON.parse(document.getElementById(name + '-data').textContent);
   }
   const dates = djangoExtract('dates').data;
   const expensesTotals = Object.values(JSON.parse("{{ expenses_totals|escapejs }}"));
   const incomeTotals = Object.values(JSON.parse("{{ income_totals|escapejs }}"));
   const assets = Object.values(JSON.parse("{{ assets|escapejs }}"));
   const expensesFlat = JSON.parse("{{ expenses|escapejs }}").data;
   const expensesFilter = "{{ account_filter|escapejs }}" || 'Expenses';
  </script>
  <script src="{% static "charts.js" %}"></script>
{% endblock %}

ledger_ui/templates/ledger_ui/error.html
{% extends "./base.html" %}

{% block title %}
  {{ block.super }} - Error
{% endblock %}

{% block content %}
  <h2>Error {{ status }}</h2>
  {% include "./error/ledger_error.html" %}
{% endblock %}

ledger_ui/templates/ledger_ui/index.html
{% include "./base.html" with menu_open=True %}

ledger_ui/templates/ledger_ui/journal.html
{% extends "./base.html" %}

{% block title %}
  {{ block.super }} - Journal
{% endblock %}

{% block content %}
  <a class="plain-link"
     href="{{ request.path }}?reverse={{ reverse | yesno:"False,True" }}{% if count != count_step %}&count={{ count }}{% endif %}{% if filter %}&filter={{ filter }}{% endif %}"
  >
    <h1 class="journal-header">Ledger entries {{ reverse | yesno:"↑,↓" }}</h1>
  </a>

  <div class="list-container">
    <form action="{{ request.path }}">
      <input id="reverse_value" name="reverse" type="hidden" value="{{ reverse }}" />
      <input name="filter" type="text" value="{{ filter }}" />
      <input type="submit" value="Filter" />
      <input type="submit" value="Show register"
             formaction="{% url 'ledger_ui:register' %}"
             onclick="document.getElementById('reverse_value').name = ''"
      />
    </form>

    {% if not reverse and count != 'all' %}
      {% include "./components/show_all.html" %}
    {% endif %}
    {% for entry in entries %}
      <div class="entry-full container">
        {% if can_revert %}
          {% if reverse and forloop.first or not reverse and forloop.last %}
            {% include "./components/entry_buttons.html" %}
          {% endif %}
        {% endif %}
        <a class="plain-link"
           href="{% url 'ledger_ui:rule' %}?payee={{ entry.payee | urlencode }}"
        >
          <pre class="card">{{ entry.body }}</pre>
        </a>
      </div>
      <details class="entry-mini">
        <summary class="container">
          {% if can_revert %}
            {% if reverse and forloop.first or not reverse and forloop.last %}
              {% include "./components/entry_buttons.html" %}
            {% endif %}
          {% endif %}
          <div class="card">
            {{ entry.date }}:
            {{ entry.payee }}
          </div>
        </summary>
        <a class="plain-link subcard"
           href="{% url 'ledger_ui:rule' %}?payee={{ entry.payee | urlencode }}"
        >
          <pre class="card">{{ entry.body }}</pre>
        </a>
      </details>
    {% endfor %}
    {% if reverse and count != 'all' %}
      {% include "./components/show_all.html" %}
    {% endif %}

    {% url "ledger_ui:submit" as fab_target %}
    {% include "./components/fab.html" with button_id="submit-fab" target=fab_target %}
  </div>
{% endblock %}

ledger_ui/templates/ledger_ui/rule.html
{% extends "./base.html" %}

{% block title %}
  {{ block.super }} - Rule {% if rule %} "{{ rule.payee }}" {% endif %}
{% endblock %}

{% block content %}
  <h2>Edit rule</h2>
  <form action="{{ request.path }}" method="post">
    {% csrf_token %}
    <fieldset>
      <legend>Conditions</legend>
      <table>
        {% for field in form.conditions %}
          <tr>
            <th>{{ field.label_tag }}</th>
            <td>
              {{ field.errors }}
              {{ field }}
            </td>
          </tr>
        {% endfor %}
      </table>
    </fieldset>
    <fieldset>
      <legend>Actions</legend>
      <table>
        {% for field in form.actions %}
          <tr>
            <th>{{ field.label_tag }}</th>
            <td>
              {{ field.errors }}
              {{ field }}
            </td>
          </tr>
        {% endfor %}
      </table>
    </fieldset>

    <input type="submit" value="Submit" />
  </form>
  {% if form.instance.pk is not None %}
    <form action="{% url 'ledger_ui:rule_delete' form.instance.pk %}" method="post">
      {% csrf_token %}
      <br />
      <input type="submit" value="Delete"
             onclick="return confirm('Really delete this rule?');"
      />
    </form>
  {% endif %}

  <div class="rule-preview-container">
    <input id="preview-button" type="button" value="Preview" />
    <ul id="rule-preview"></ul>
  </div>

  <script>
   document.getElementById('preview-button')
           .addEventListener(
             'click',
             function () {
               let payee = document.getElementById('id_payee').value;
               let note = document.getElementById('id_note').value;
               let req = new XMLHttpRequest();
               req.open(
                 'GET',
                 "{% url 'ledger_query:transactions' %}"
                 + "?payee=" + encodeURIComponent(payee)
                 + "&note=" + encodeURIComponent(note)
                 + "&count=11",
                 true
               );
               req.onreadystatechange = function (aEvt) {
                 if (req.readyState == 4) {
                   if (req.status == 200) {
                     let target = document.getElementById('rule-preview');
                     while (target.firstChild) {
                       target.removeChild(target.firstChild);
                     }

                     let entries = JSON.parse(req.responseText).entries;
                     if (entries.length > 0) {
                       for (let entry in entries.slice(0, 10)) {
                         let item = document.createElement('li');
                         item.textContent = (
                           entries[entry].date
                           + ': '
                           + entries[entry].payee
                         );
                         target.appendChild(item);
                       }
                       if (entries.length > 10) {
                         let item = document.createElement('li');
                         item.textContent = ('...');
                         target.appendChild(item);
                       }
                     } else {
                       let item = document.createElement('li');
                       item.textContent = ('[no matches]');
                       target.appendChild(item);
                     }
                   }
                 }
               };
               req.send(null);
             }
           );
  </script>
{% endblock %}

ledger_ui/templates/ledger_ui/rules.html
{% extends "./base.html" %}

{% block title %}
  {{ block.super }} - Rules
{% endblock %}

{% block content %}
  <div class="rules-desktop">
    <h2>Rules</h2>
    <form action="{% url 'ledger_ui:rule' %}">
      <input type="submit" value="New" />
    </form>
    <table class="ledger-table">
      <tr>
        <th>Payee</th>
        <th>Note</th>
        <th class="table-separator">New payee</th>
        <th>New note</th>
        <th>Account</th>
      </tr>
      {% for rule in object_list %}
        <tr class="rule-row">
          <td>
            <a href="{% url 'ledger_ui:rule' rule.pk %}">{{ rule.payee }}</a>
          </td>
          <td> {{ rule.note }} </td>
          <td class="table-separator"> {{ rule.new_payee }} </td>
          <td> {{ rule.new_note }} </td>
          <td> {{ rule.account }} </td>
          <td>
            <form action="{% url 'ledger_ui:rule_delete' rule.pk %}" method="post">
              {% csrf_token %}
              <input type="submit" value="Delete"
                     onclick="return confirm('Really delete this rule?');"
              />
            </form>
          </td>
        </tr>
      {% endfor %}
    </table>
  </div>

  <div class="rules-mobile list-container">
    <h2>Rules</h2>
    {% for rule in object_list %}
      <details>
        <summary class="rule-details-summary card noselect">
          {{ rule.payee }}
        </summary>
        <a class="plain-link rule-details subcard" href="{% url 'ledger_ui:rule' rule.pk %}">
          <dl class="card">
            {% if rule.new_payee %}
              <dt>New payee</dt>
              <dd>{{ rule.new_payee }}</dd>
            {% endif %}
            {% if rule.note %}
              <dt>Note</dt>
              <dd>{{ rule.note }}</dd>
            {% endif %}
            {% if rule.new_note %}
              <dt>New note</dt>
              <dd>{{ rule.new_note }}</dd>
            {% endif %}
            {% if rule.account %}
              <dt>Account</dt>
              <dd>{{ rule.account }}</dd>
            {% endif %}
          </dl>
        </a>
      </details>
    {% endfor %}
  </div>

  {% url 'ledger_ui:rule' as fab_target %}
  {% include "./components/fab.html" with button_id="rules-fab" target=fab_target %}
{% endblock %}