ledger/urls.py
from django.contrib import admin
from django.urls import path, include

from ledger_ui.views import index

urlpatterns = [
    path('', index),
    path('admin/', admin.site.urls),
    path('ledger/ui/', include('ledger_ui.urls')),
    path('ledger/submit/', include('ledger_submit.urls')),
    path('ledger/query/', include('ledger_query.urls')),
    path('accounts/', include('accounts.urls')),
]

ledger_ui/urls.py
from django.urls import path

from . import views

app_name = 'ledger_ui'
urlpatterns = [
    path('', views.index, name='index'),
    path('journal/', views.journal, name='journal'),
    path('submit/', views.submit, name='submit'),
    path('balance/', views.balance, name='balance'),
    path('charts/', views.charts, name='charts'),
    path('register/', views.register, name='register'),
    path('rules/', views.RuleIndexView.as_view(), name='rules'),
    path('rule/', views.RuleCreateView.as_view(), name='rule'),
    path('rule/<int:pk>/', views.RuleEditView.as_view(), name='rule'),
    path('rule/<int:pk>/delete/', views.RuleDeleteView.as_view(), name='rule_delete'),
]

accounts/models.py
from django.contrib.auth.models import User
from django.db import models

from fido2.ctap2 import AttestedCredentialData

class FIDOCredential(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )
    raw_credential = models.BinaryField()
    credential_name = models.CharField(max_length=512, blank=True)

    @property
    def credential(self):
        return AttestedCredentialData(self.raw_credential)

    @credential.setter
    def credential(self, credential):
        self.raw_credential = bytes(credential)

    class Meta:
        unique_together = (('user', 'raw_credential'))

ledger_ui/models.py
from django.contrib.auth.models import User
from django.db import models

import pickle


class LedgerPath(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        primary_key=True,
        related_name="ledger_path",
    )
    path = models.CharField(max_length=1024)

    def __str__(self):
        return "{}: {}".format(self.user, self.path)


class Undo(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        primary_key=True,
    )

    last_entry_pickle = models.BinaryField()
    old_position = models.PositiveIntegerField()
    new_position = models.PositiveIntegerField()

    @property
    def last_entry(self):
        return pickle.loads(self.last_entry_pickle)

    @last_entry.setter
    def last_entry(self, entry):
        self.last_entry_pickle = pickle.dumps(entry)

ledger_ui/forms.py
from django import forms
from django.conf import settings
from django.forms import formset_factory, BaseFormSet
from django.utils.translation import gettext as _

import datetime
import re

from . import fields
from ledger_submit.models import Rule


class AccountForm(forms.Form):

    name = forms.CharField(widget=fields.ListTextWidget(
        name='accounts',
        data_list=None,
        attrs={'class': 'name-input'},
    ))
    amount = forms.DecimalField(
        decimal_places=2,
        required=False,
        widget=forms.NumberInput(attrs={'class': 'amount-input'}),
    )
    currency = forms.CharField(
        required=False,
        widget=fields.ListTextWidget(
            name='currencies',
            data_list=None,
            attrs={
                'tabindex': -1,
                'size': 5,
                'class': 'currency-input',
            },
        ),
    )

    field_order = ['name', 'amount', 'currency']

    def __init__(self, *args, default_currency=None, **kwargs):
        if default_currency is None:
            default_currency = settings.LEDGER_DEFAULT_CURRENCY
        initial = kwargs.pop('initial', {})
        if initial.get('amount') is None:
            initial['currency'] = default_currency
        super().__init__(*args, initial=initial, **kwargs)


class BaseAccountFormSet(BaseFormSet):

    def clean(self):
        if any(self.errors):
            return

        missing_amount_count = [
            form.cleaned_data.get('amount')
            for form in self.forms
        ].count(None)
        if missing_amount_count > 1:
            raise forms.ValidationError(
                _("Only one account can have the amount omitted.")
            )


AccountFormSet = formset_factory(
    AccountForm,
    formset=BaseAccountFormSet,
    min_num=2,
    extra=0,
    validate_min=True,
)


class SubmitForm(forms.Form):

    date = forms.DateField(initial=datetime.date.today)
    payee = forms.CharField(max_length=512)
    note = forms.CharField(
        required=False,
        widget=forms.Textarea(
            attrs={
                'tabindex': -1,
                'rows': 1,
                'cols': 20,
            },
        ),
    )

    amend = forms.BooleanField(
        # Even though it's a BooleanField, the HiddenInput widget is
        # textual. False would be cast to "False" which is true, so
        # let's use a false string instead.
        initial='',
        required=False,
        widget=forms.HiddenInput(),
    )
    save_rule = forms.BooleanField(
        label="Save as a new rule",
        initial=False,
        required=False,
    )

    def top_fields(self):
        return (
            self[field]
            for field in ['date', 'payee', 'note']
        )

    def __init__(self, *args, payees, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['payee'].widget = fields.ListTextWidget(
            name='payees',
            data_list=payees,
            attrs={'autofocus': ''},
        )


class RuleModelForm(forms.ModelForm):

    class Meta:
        model = Rule
        exclude = ['user']

    def conditions(self):
        return (
            self[field]
            for field in ['payee', 'note']
        )

    def actions(self):
        return (
            self[field]
            for field in ['new_payee', 'new_note', 'account']
        )

    def __init__(self, *args, accounts, payees, user, **kwargs):
        super().__init__(*args, **kwargs)

        self.user = user

        self.fields['payee'].widget = fields.ListTextWidget(
            name='payee',
            data_list=map(re.escape, payees),
        )
        self.fields['note'].widget = forms.Textarea(
            attrs={
                'rows': 1,
                'cols': 20,
            },
        )
        self.fields['new_payee'].widget = fields.ListTextWidget(
            name='new_payee',
            data_list=payees,
        )
        self.fields['new_note'].widget = forms.Textarea(
            attrs={
                'rows': 1,
                'cols': 20,
            },
        )
        self.fields['account'].widget = fields.ListTextWidget(
            name='account',
            data_list=accounts,
        )

    def clean(self):
        errors = []
        cleaned_data = super().clean()

        payee = cleaned_data['payee']
        user = self.user
        try:
            Rule.objects.exclude(
                pk=self.instance.pk,
            ).get(
                payee=payee,
                user=user,
            )
        except Rule.DoesNotExist:
            pass
        else:
            errors.append(
                forms.ValidationError(
                    _("Non-unique data: payee=%(payee)s, user=%(user)s."),
                    params={'payee': payee, 'user': user},
                    code='invalid',
                )
            )

        if errors:
            raise forms.ValidationError(errors)

ledger_ui/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.db.models.functions import Lower
from django.http import Http404, HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView

import pandas as pd
import re

from .forms import SubmitForm, RuleModelForm, AccountFormSet
from .models import Undo
from ledger_submit.models import Rule
from utils import ledger_api


def index(request):
    return render(
        request,
        'ledger_ui/index.html',
    )


@login_required
def journal(request):
    if request.method == 'POST':
        if request.POST.get('revert'):
            undo = get_object_or_404(Undo, pk=request.user)

            ledger_path = request.user.ledger_path.path
            journal = ledger_api.Journal(ledger_path, undo)

            try:
                journal.revert()
            except journal.CannotRevert:
                return render(
                    request,
                    'ledger_ui/error/cannot_revert.html',
                    status=409,
                )

    entries = list(ledger_api.Journal(request.user.ledger_path.path))


    entry_filter = request.GET.get('filter', '')
    if entry_filter:
        entries = [
            entry
            for entry in entries
            if entry_filter.lower() in entry['body'].lower()
        ]

    count = request.GET.get('count', settings.LEDGER_ENTRY_COUNT)
    try:
        count = int(count)
    except ValueError:
        if count is not None and count != 'all':
            return HttpResponse(
                '<h1>Unprocessable Entity</h1> Bad count.',
                status=422,
            )
    if count != 'all' and len(entries) <= count:
        count = 'all'
    if count != 'all':
        entries = entries[-count:]

    reversed_sort = request.GET.get('reverse', 'true').lower() not in ['false', '0']
    if reversed_sort:
        entries = reversed(entries)

    ledger_path = request.user.ledger_path.path
    journal = ledger_api.Journal(ledger_path)
    try:
        undo = Undo.objects.get(pk=request.user)
    except Undo.DoesNotExist:
        pass
    else:
        journal.last_data = undo

    return render(
        request,
        'ledger_ui/journal.html',
        {
            'entries': entries,
            'reverse': reversed_sort,
            'count': count,
            'filter': entry_filter,
            'count_step': settings.LEDGER_ENTRY_COUNT,
            'can_revert': not entry_filter and journal.can_revert(),
        },
    )


@login_required
def charts(request):
    ledger_path = request.user.ledger_path.path

    csv = ledger_api.Journal(ledger_path).csv(
        '--real',
        '--monthly',
        '-X', settings.LEDGER_DEFAULT_CURRENCY,
    )
    df = pd.read_csv(
        csv,
        header=None,
        names=[
            'date', 'code', 'payee', 'account', 'currency', 'amount',
            'reconciled', 'note',
        ],
        usecols=['date', 'payee', 'account', 'amount'],
        parse_dates=['date'],
    )
    if len(df) == 0:
        return render(
            request,
            'ledger_ui/charts.html',
        )

    assets = df[df['account'].str.contains("^Assets:|^Liabilities:")]
    income = df[df['account'].str.contains("^Income:")]

    account_filter = request.GET.get('account_filter', '')
    if account_filter:
        expenses = df[df['account'].str.contains(
            account_filter,
            case=False,
        )].copy()
    else:
        expenses = df[df['account'].str.contains("^Expenses:")].copy()

    date_grouped_assets = assets[['date', 'amount']].groupby('date').sum()
    date_grouped_expenses = expenses[['date', 'amount']].groupby('date').sum()
    date_grouped_income = income[['date', 'amount']].groupby('date').sum()

    date_range = pd.date_range(df['date'].min(), df['date'].max(), freq='MS')
    date_grouped_assets = date_grouped_assets.reindex(date_range, fill_value=0)
    date_grouped_expenses = date_grouped_expenses.reindex(date_range, fill_value=0)
    date_grouped_income = date_grouped_income.reindex(date_range, fill_value=0)

    date_grouped_assets['amount'] = date_grouped_assets['amount'].cumsum()
    expenses['date'] = expenses['date'].dt.strftime("%Y-%m")

    return render(
        request,
        'ledger_ui/charts.html',
        {
            'dates': {'data': date_range.strftime('%Y-%m').to_series().to_list()},
            'expenses_totals': date_grouped_expenses['amount'].round(2).to_json(),
            'income_totals': (-date_grouped_income['amount']).round(2).to_json(),
            'expenses': (
                expenses[['date', 'account', 'amount']].to_json(
                    orient='table', index=False)),
            'assets': date_grouped_assets['amount'].round(2).to_json(),
            'account_filter': account_filter,
        },
    )


@login_required
def submit(request):
    ledger_path = request.user.ledger_path.path
    journal = ledger_api.Journal(ledger_path)
    ledger_errors = False

    try:
        accounts = journal.accounts()
        currencies = journal.currencies()
        payees = journal.payees()
    except journal.LedgerCliError as e:
        accounts = currencies = payees = []
        ledger_errors = e.__cause__

    if request.method == 'POST':
        form = SubmitForm(
            request.POST,
            payees=payees,
        )
        formset = AccountFormSet(
            request.POST,
        )
        if form.is_valid() and formset.is_valid():
            validated = form.cleaned_data
            entry = ledger_api.Entry(
                date=validated['date'],
                payee=validated['payee'],
                note=validated['note'],
                accounts=[
                    (account['name'], account['amount'], account['currency'])
                    for account in formset.cleaned_data
                    if account.get('name')
                ],
            )

            if validated['amend']:
                undo = get_object_or_404(Undo, pk=request.user)
                journal.last_data = undo

                if validated['save_rule']:
                    Rule.objects.create(
                        user=request.user,
                        payee=re.escape(undo.last_entry.payee),
                        note=(
                            undo.last_entry.note
                            if undo.last_entry.note != entry.note
                            else ''
                        ),
                        new_payee=entry.payee,
                        new_note=(
                            entry.note
                            if undo.last_entry.note != entry.note
                            else ''
                        ),
                        account=entry.accounts[0][0],
                    )

                try:
                    journal.revert()
                except journal.CannotRevert:
                    return render(
                        request,
                        'ledger_ui/error/cannot_revert.html',
                        status=409,
                    )

            old, new = journal.append(entry)
            Undo.objects.update_or_create(
                pk=request.user.id,
                defaults={
                    'last_entry': entry,
                    'old_position': old,
                    'new_position': new,
                },
            )
            return redirect('ledger_ui:journal')

    else:
        amend = request.GET.get('amend', 'false').lower() not in ['false', '0']
        if amend:
            last_entry = get_object_or_404(Undo, pk=request.user).last_entry
            form = SubmitForm(
                {
                    'date': last_entry.date,
                    'payee': last_entry.payee,
                    'note': last_entry.note,
                    'amend': True,
                },
                payees=payees,
            )
            default_currency = settings.LEDGER_DEFAULT_CURRENCY
            for account in last_entry.accounts:
                if account.amount is not None:
                    default_currency = account.currency
                    break
            formset = AccountFormSet(
                form_kwargs={
                    'default_currency': default_currency,
                },
                initial=[
                    account._asdict()
                    for account in last_entry.accounts
                ],
            )
        else:
            form = SubmitForm(payees=payees)
            formset = AccountFormSet(
                initial=[
                    {'name': settings.LEDGER_DEFAULT_TO},
                    {'name': settings.LEDGER_DEFAULT_FROM},
                ]
            )

    return render(
        request,
        'ledger_ui/submit.html',
        {
            'form': form,
            'formset': formset,
            'accounts': accounts,
            'currencies': currencies,
            'ledger_errors': ledger_errors,
        },
    )


@login_required
def balance(request):
    ledger_path = request.user.ledger_path.path

    csv = ledger_api.Journal(ledger_path).csv()
    df = pd.read_csv(
        csv,
        header=None,
        names=[
            'date', 'code', 'payee', 'account', 'currency', 'amount',
            'reconciled', 'note',
        ],
        usecols=['account', 'currency', 'amount'],
    )

    search = request.GET.get('filter', '')
    if search:
        df = df[df['account'].str.contains(search, case=False)]

    if len(df) == 0:
        return render(
            request,
            'ledger_ui/balance.html',
            {
                'accounts': [],
                'filter': search,
            },
        )

    balance = df.groupby(['account', 'currency']).sum()

ledger_ui/templates/ledger_ui/components/entry_buttons.html
{% load static %}

<div class="entry-buttons-container">
  <div class="entry-buttons">
    <form action="{% url 'ledger_ui:submit' %}" method="GET">
      <input class="entry-button amend"
             type="submit" value="" title="Amend"
             style="background-image: url('{% static 'images/amend.png' %}');"
      />
      <input name="amend" type="hidden" value="true" />
    </form>
    <form action="{% url 'ledger_ui:journal' %}" method="POST">
      {% csrf_token %}
      <input class="entry-button revert"
             type="submit" value="" title="Revert"
             style="background-image: url('{% static 'images/delete.png' %}');"
             onclick="return confirm('Really delete this entry?');"
      />
      <input name="revert" type="hidden" value="true" />
    </form>
  </div>
</div>

ledger_ui/templates/ledger_ui/components/fab.html
{% load static %}

<div id="{{ button_id }}" class="material-button-container">
  <a href="{{ target }}">
    <img class="material-button" src="{% static 'images/add.png' %}" />
  </a>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.11/lodash.min.js"></script>
<script>
 let lastScrollTop = 0;
 window.onscroll = _.throttle(
   function (e) {
     const button = document.getElementById("{{ button_id }}");
     const scrollTop = document.body.scrollTop || document.documentElement.scrollTop;
     const dy = scrollTop - lastScrollTop;
     if (dy < 0) {
       button.classList.remove("hidden");
     } else if (dy > 0) {
       button.classList.add("hidden");
     } else {
       /* Horizontal scrolling. */
     }
     lastScrollTop = scrollTop;
   },
   100
 );
</script>

ledger_ui/templates/ledger_ui/components/menu.html
{% load static %}

<script>
 function onMenu () {
   const hamburger = document.getElementById('hamburger');
   hamburger.classList.toggle('is-active');
 }
</script>

<details class="collapsible-menu-container"
         {% if menu_open %}open{% endif %}
         ontoggle="onMenu()"
>
  <summary class="collapsible-menu-button noselect">
    <div id="hamburger" class="hamburger hamburger--arrowalt" type="button">
      <span class="hamburger-box">
        <span class="hamburger-inner"></span>
      </span>
    </div>

    Ledger Web
  </summary>
  <div class="collapsible-menu">
    {% include './menu_base.html' %}
  </div>
</details>
<div class="constant-menu">
  {% include './menu_base.html' %}
</div>

ledger_ui/templates/ledger_ui/components/menu_base.html
<nav class="menu-grid">
  {% if user.is_authenticated %}
    <div class="menu-element menu-user">
      User: <span>
      <span class="username">{{ user }}</span>
      {% if fido_enabled %}
        <a class="plain-link" href="{% url 'register-fido' %}">
          {% if user.fidocredential_set.count > 0 %}
            🔒
          {% else %}
            🔓
          {% endif %}
        </a>
      {% endif %}
      </span>
    </div>
    <a class="menu-element menu-login" href="{% url 'logout' %}">Logout</a>
  {% else %}
    <a class="menu-element menu-login" href="{% url 'login' %}">Login</a>
  {% endif %}
  <a class="menu-element menu-journal" href="{% url 'ledger_ui:journal' %}">Journal</a>
  <a class="menu-element menu-charts" href="{% url 'ledger_ui:charts' %}">Charts</a>
  <a class="menu-element menu-balance" href="{% url 'ledger_ui:balance' %}">Balance</a>
  <a class="menu-element menu-submit" href="{% url 'ledger_ui:submit' %}">Submit</a>
  <a class="menu-element menu-rules" href="{% url 'ledger_ui:rules' %}">Rules</a>
</nav>

ledger_ui/templates/ledger_ui/components/show_all.html
<a class="plain-link"
   href="{{ request.path }}?{% if not reverse %}reverse={{ reverse }}&{% endif %}{% if filter %}filter={{ filter }}&{% endif %}count=all"
>
  <div class="card show-all">Show all…</div>
</a>

ledger_ui/templates/ledger_ui/components/transaction.html
{% load static %}

<div class="transaction-account-form"
     {% if id %} id="{{ id }}" {% endif %}
>
  <div class="{{ form.name.label }}-grid-item">
    {{ form.name.label_tag }} {{ form.name }}
  </div>
  <div class="{{ form.amount.label }}-grid-item">
    {{ form.amount.label_tag }} {{ form.amount }}
  </div>
  <div class="{{ form.currency.label }}-grid-item">
    {{ form.currency }}
  </div>
  <button tabindex="-1"
          onclick="deleteAccount(this, event)"
          class="transaction-account-form-delete"
          style="background-image: url('{% static 'images/delete.png' %}');"
  ></button>
</div>